export const category: any = [
    {value: 'action' , label: 'Action & Adventure'},
    { value: 'activity', label: 'Activity Books'},
    {value: 'animal', label: 'Animals'},
    {value: 'anthologies', label: 'Anthologies'},
    {value: 'art', label: 'Arts & Literature'},
    {value: 'car', label: 'Cars & Trucks'},
    {value: 'classics', label: 'Classics'},
    {value: 'contemporaty', label: 'Contemporary'},
    {value: 'culture', label: 'Culture'},
    {value: 'european', label: 'European'},
    {value: 'language', label: 'Foreign Language'},
    {value: 'fiction', label: 'Genre Fiction'},
    {value: 'historical', label: 'Historical'},
    {value: 'uncategorized', label: 'Uncategorized'},
]